version: '3.8'
services:
  dotnet_main:
    image: dotnet-web
    container_name: dotnet_main
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "8001:80"
    environment:
      ConnectionStrings__Default: host=localhost;Port=5432;Database=postgresDB;User Id=admin;Password=admin;
    depends_on:
      - dotnet_postgres
        
  dotnet_postgres:
    image: postgres:alpine
    container_name: dotnet_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgresDB
    
#  dotnet_rabbitmq:
#    image: rabbitmq:3-alpine
#    
#  dotnet_minio:
#    image: minio/minio:latest
#    
#  dotnet_mongodb:
#    image: mongo:latest
#    
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
#    
#  dotnet_mailing:
#    image: dotnet-web
#    
#  dotnet_storage:
#    image: dotnet-web